# Generated by Django 6.0.1 on 2026-02-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_usermedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='Password2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
