# Generated by Django 6.0.1 on 2026-02-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_usermedia_password2_alter_usermedia_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermedia',
            name='Password2',
        ),
    ]
